export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[#030712] text-slate-100 py-16 px-6">
      <div className="max-w-4xl mx-auto">
        <div className="mb-12">
          <Link href="/" className="text-emerald-400 hover:text-emerald-300 text-sm font-medium transition-colors">
            ← Back to LedgerFlow
          </Link>
        </div>

        <div className="prose prose-invert prose-emerald max-w-none">
          <h1 className="text-4xl font-black text-white tracking-tight mb-6">Terms of Service</h1>
          <p className="text-slate-400 text-sm mb-8">Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>

          <div className="space-y-8 text-slate-300">
            <section>
              <h2 className="text-xl font-bold text-white">1. Introduction</h2>
              <p className="text-slate-400 leading-relaxed">
                Welcome to LedgerFlow. By using our service, you agree to these Terms of Service. Please read them carefully.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white">2. Definitions</h2>
              <ul className="list-disc list-inside text-slate-400 space-y-2">
                <li><strong>Service</strong> – The LedgerFlow platform for parsing bank statements and generating CSV exports.</li>
                <li><strong>User</strong> – Any individual or entity using our Service.</li>
                <li><strong>Content</strong> – Any data, documents, or information uploaded to or generated by the Service.</li>
                <li><strong>Pages</strong> – Individual pages within a PDF document processed by the Service.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white">3. Account &amp; Subscription</h2>
              <p className="text-slate-400 leading-relaxed">
                To access full features, you must create an account and choose a subscription plan. Plans include:
              </p>
              <ul className="list-disc list-inside text-slate-400 space-y-2 mt-2">
                <li><strong>Free Trial:</strong> 5 pages upon registration</li>
                <li><strong>Starter:</strong> $12/mo – 50 pages</li>
                <li><strong>Pro:</strong> $29/mo – 300 pages</li>
                <li><strong>Enterprise:</strong> $49/mo – Unlimited pages</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white">4. Usage &amp; Responsibility</h2>
              <p className="text-slate-400 leading-relaxed">
                You are responsible for all Content uploaded to LedgerFlow. You retain full ownership of your data. We process your documents solely for the purpose of extracting transaction data and do not store uploaded files after processing.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white">5. Payment &amp; Billing</h2>
              <p className="text-slate-400 leading-relaxed">
                Subscriptions are billed monthly or yearly depending on your selected plan. Payments are processed through Lemon Squeezy. All fees are non-refundable unless otherwise required by law.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white">6. Acceptable Use</h2>
              <p className="text-slate-400 leading-relaxed">
                You agree not to:
              </p>
              <ul className="list-disc list-inside text-slate-400 space-y-2 mt-2">
                <li>Use the Service for any illegal purpose</li>
                <li>Upload malicious or harmful files</li>
                <li>Attempt to bypass our payment or page limits</li>
                <li>Reverse engineer or resell the Service</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white">7. Intellectual Property</h2>
              <p className="text-slate-400 leading-relaxed">
                LedgerFlow and its logos are protected by copyright and trademark laws. You may not copy, modify, or distribute our code without explicit permission.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white">8. Disclaimer of Warranties</h2>
              <p className="text-slate-400 leading-relaxed">
                The Service is provided "as is" and "as available." While we strive for accuracy, we do not guarantee that OCR extraction will be 100% error-free.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white">9. Limitation of Liability</h2>
              <p className="text-slate-400 leading-relaxed">
                LedgerFlow is not liable for any indirect, incidental, or consequential damages arising from your use of the Service.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white">10. Changes to These Terms</h2>
              <p className="text-slate-400 leading-relaxed">
                We may update these Terms from time to time. We will notify users of significant changes via email or through the Service.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white">11. Contact</h2>
              <p className="text-slate-400 leading-relaxed">
                For questions, email us at <a href="mailto:support@ledgerflow.com" className="text-emerald-400 hover:underline">support@ledgerflow.com</a>.
              </p>
            </section>
          </div>
        </div>
      </div>
    </main>
  );
}

// Need to import Link
import Link from 'next/link';